### ISSUE TITLE
Completed  module 02 assignment

### ISSUE THREAD

**Issue by ljc3084** [ds4owd-001/md-02-assignments-ljc3084#1]
@larnsce @mianzg @sskorik01 Very interesting module, thanks for all the assignment looking forward to the next one.

**Comment by larnsce** [comment]
Hi @ljc3084, thank you for working through the assignment. You haven't yet committed and pushed your code (your code in md-02a-data-visualization.qmd has not been updated on GitHub). You have to commit and push from posit.cloud to confirm you have finished your assignment.
